# -*- coding: utf-8 -*-
"""practica8_pt1.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1QGwO5BzczAyOpJGl2Kdln1mYN57sQpFH
"""

def unir_archivos(archivo_destino, *archivos_fuente):
  """
  Une archivos
  """
  with open(archivo_destino, 'a') as destino:
        for archivo_fuente in archivos_fuente:
            with open(archivo_fuente, 'r') as fuente:
                destino.write(fuente.read())

unir_archivos('nah', 'train.nah', 'dev.nah')

unir_archivos('es', 'train.es', 'dev.es')